version: "3.8"
services:
  nextcloud:
    image: nextcloud:apache
    container_name: nextcloud
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - REDIS_HOST=nextcloud-redis
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - OVERWRITEPROTOCOL=https
    security_opt:
      - no-new-privileges:true
    depends_on:
      - nextcloud-mariadb
      - nextcloud-redis
    networks:
      - homeserver
    volumes:
      - nextcloud:/var/www/html

  nextcloud-mariadb:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    container_name: nextcloud-mariadb
    networks:
      - homeserver
    volumes:
      - nextcloud-db:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}

  nextcloud-redis:
    image: redis:alpine
    restart: always
    container_name: nextcloud-redis
    networks:
      - homeserver
    volumes:
      - nextcloud-redis:/data

  nextcloud-cron:
    image: rcdailey/nextcloud-cronjob
    restart: always
    network_mode: none
    depends_on:
      - nextcloud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NEXTCLOUD_CONTAINER_NAME=nextcloud
      - NEXTCLOUD_EXEC_SHELL=sh

networks:
  homeserver:
    name: homeserver
    external: true

volumes:
  nextcloud:
  nextcloud-db:
  nextcloud-redis: