version: "3.8"

services:
  # Cloudflare Tunnel - exposes all services
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    security_opt:
      - no-new-privileges:true
    networks:
      - homeserver

  # Portainer for container management
  portainer:
    image: portainer/portainer-ce:2.32.0
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000  # Keep for direct access if tunnel fails
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    env_file:
      - .env
    container_name: portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - homeserver

networks:
  homeserver:
    name: homeserver
    driver: bridge

volumes:
  portainer_data:
