version: "3.8"

services:
  registry:
    image: registry:2
    container_name: registry
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /volume1/docker/registry/data:/var/lib/registry/
    environment:
      STORAGE_PATH: /var/lib/registry/
    networks:
      - homeserver

  dockerhub:
    image: konradkleine/docker-registry-frontend:v2
    restart: always
    container_name: dockerhub
    environment:
      ENV_DOCKER_REGISTRY_USE_SSL: 1
      ENV_DOCKER_REGISTRY_PORT: 443
    networks:
      - homeserver
    security_opt:
      - no-new-privileges:true

networks:
  homeserver:
    name: homeserver
    external: true
