version: "3.8"

services:
  registry:
    image: registry:2
    container_name: registry
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /volume1/docker/registry/data:/var/lib/registry/
    environment:
      STORAGE_PATH: /var/lib/registry/
    networks:
      - homeserver
    labels:
      - my.zone=homeserver
      - traefik.enable=true
      - traefik.http.routers.registry.rule=Host(`registry.${SERVER_DOMAIN}`)
      - traefik.http.routers.registry.entrypoints=websecure
      - traefik.http.routers.registry.tls.certresolver=myresolver
      - traefik.http.services.registry.loadbalancer.server.port=5000
      - traefik.docker.network=homeserver

  dockerhub:
    image: konradkleine/docker-registry-frontend:v2
    restart: always
    container_name: dockerhub
    environment:
      ENV_DOCKER_REGISTRY_USE_SSL: 1
      ENV_DOCKER_REGISTRY_PORT: 443
    networks:
      - homeserver
    security_opt:
      - no-new-privileges:true
    labels:
      - my.zone=homeserver
      - traefik.enable=true
      - traefik.http.routers.dockerhub.rule=Host(`dockerhub.${SERVER_DOMAIN}`)
      - traefik.http.routers.dockerhub.entrypoints=websecure
      - traefik.http.routers.dockerhub.tls.certresolver=myresolver
      - traefik.http.services.dockerhub.loadbalancer.server.port=80
      - traefik.docker.network=homeserver

networks:
  homeserver:
    name: homeserver
    external: true
