version: "3.8"
services:
  cyberchef:
    container_name: cyberchef
    image: mpepping/cyberchef:v9.37.3
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - homeserver

networks:
  homeserver:
    name: homeserver
    external: true