version: "3.8"
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor@sha256:ddadf3e2fd880deb4e0f3606d34a0d9da1165e3801116075d98a1901635dc9e8
    container_name: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /volume1/@docker:/var/lib/docker:ro
    networks:
      - homeserver
    security_opt:
      - no-new-privileges:true

networks:
  homeserver:
    name: homeserver
    external: true