version: "3.8"

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - gluetun_config:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER:-surfshark}
      - VPN_TYPE=${VPN_TYPE:-wireguard}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - TZ=${TZ:-UTC}
    networks:
      - homeserver
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  # Torrent Client (through VPN)
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - WEBUI_PORT=8080
    volumes:
      - qbittorrent_config:/config
      - media_downloads:/downloads
    depends_on:
      - gluetun
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  # Usenet Client
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - sabnzbd_config:/config
      - media_downloads:/downloads
    networks:
      - homeserver
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  # Indexer Manager
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - prowlarr_config:/config
    networks:
      - homeserver
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  # TV Show Manager
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - sonarr_config:/config
      - media_data:/data
    networks:
      - homeserver
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  # Movie Manager
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - radarr_config:/config
      - media_data:/data
    networks:
      - homeserver
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    
  # Subtitle Manager
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - bazarr_config:/config
      - media_data:/data
    networks:
      - homeserver
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  # Jellyfin Media Server
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - jellyfin_config:/config
      - media_data:/data
      - jellyfin_cache:/cache
    networks:
      - homeserver
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # GPU support (uncomment if you have Intel/AMD GPU)
    # devices:
    #   - /dev/dri:/dev/dri

  # Plex Media Server
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - plex_config:/config
      - media_data:/data
    networks:
      - homeserver
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # GPU support (uncomment if you have Intel/AMD GPU)
    # devices:
    #   - /dev/dri:/dev/dri

  # Media Request Manager
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - LOG_LEVEL=info
    volumes:
      - jellyseerr_config:/app/config
    networks:
      - homeserver
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  homeserver:
    name: homeserver
    external: true

volumes:
  gluetun_config:
  qbittorrent_config:
  sabnzbd_config:
  prowlarr_config:
  sonarr_config:
  radarr_config:
  bazarr_config:
  jellyfin_config:
  jellyfin_cache:
  plex_config:
  jellyseerr_config:
  media_downloads:
  media_data: