version: "3.8"

services:
  gogs:
    restart: always
    image: gogs/gogs:0.12
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /volume1/docker/gogs/data:/data
    container_name: gogs
    security_opt:
      - no-new-privileges:true
    networks:
      - homeserver
    labels:
      - my.zone=homeserver
      - traefik.enable=true
      - traefik.http.routers.gogs.rule=Host(`gogs.${SERVER_DOMAIN}`)
      - traefik.http.routers.gogs.entrypoints=websecure
      - traefik.http.routers.gogs.tls.certresolver=myresolver
      - traefik.http.services.gogs.loadbalancer.server.port=3000
      - traefik.docker.network=homeserver

networks:
  homeserver:
    name: homeserver
    external: true
