version: "3.8"

services:
  gogs:
    restart: always
    image: gogs/gogs:0.12
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - gogs-volume:/data
    container_name: gogs
    security_opt:
      - no-new-privileges:true
    networks:
      - homeserver

networks:
  homeserver:
    name: homeserver
    external: true

volumes:
  gogs-volume: