version: "3.8"

services:
  pypi-server:
    image: pypiserver/pypiserver:latest
    container_name: pypiserver
    volumes:
      - /volume1/docker/pypiserver/packages:/data/packages
    command: -P . -a . /data/packages
    restart: always
    user: root
    networks:
      - homeserver
    security_opt:
      - no-new-privileges:true

networks:
  homeserver:
    name: homeserver
    external: true