# https://github.com/alexta69/metube#configuration-via-environment-variables

version: '3.8'
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: always
    volumes:
      - metube_downloads:/downloads
    security_opt:
      - no-new-privileges:true
    networks:
      - homeserver
    environment:
      - PUID=1000
      - PGID=1000

networks:
  homeserver:
    name: homeserver
    external: true

volumes:
  metube_downloads: