version: '3.8'
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: always
    networks:
      - homeserver
    volumes:
      - /volume1/docker/metube/downloads:/downloads
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=8081
    labels:
      - "my.zone=homeserver"
      - traefik.enable=true
      - traefik.http.routers.metube.rule=Host(`metube.${SERVER_DOMAIN}`)
      - traefik.http.routers.metube.entrypoints=websecure
      - traefik.http.routers.metube.tls.certresolver=myresolver
      - traefik.http.services.metube.loadbalancer.server.port=8081
      - traefik.docker.network=homeserver

networks:
  homeserver:
    name: homeserver
    external: true

