# https://github.com/alexta69/metube#configuration-via-environment-variables

version: '3.8'
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: always
    network_mode: "container:gluetun"
    volumes:
      - /volume1/docker/metube/downloads:/downloads
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000

networks:
  homeserver:
    name: homeserver
    external: true

