version: "3.8"

services:
  kuma:
    image: louislam/uptime-kuma:1
    container_name: kuma
    restart: always
    volumes:
      - /volume1/docker/uptime-kuma/data:/app/data
    networks:
      - homeserver
    security_opt:
      - no-new-privileges:true

networks:
  homeserver:
    name: homeserver
    external: true
