version: "3.8"

volumes:
  kuma:

services:
  kuma:
    image: louislam/uptime-kuma:1
    container_name: kuma
    restart: always
    volumes:
      - kuma:/app/data
    networks:
      - homeserver
    security_opt:
      - no-new-privileges:true

networks:
  homeserver:
    name: homeserver
    external: true
