version: '3.8'

services:
  # uses sqlite which is fine by me
  # https://docs.n8n.io/hosting/databases/supported-databases-settings/#sqlite

  # potentially todo: add cloudflared with a custom subdomain with a tunnel for webhooks
  n8n:
    image: n8nio/n8n
    restart: always
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_LOG_OUTPUT=console,file
      - N8N_LOG_LEVEL=debug
    volumes:
      - /volume1/docker/n8n/storage:/home/node/
    security_opt:
      - no-new-privileges:true
    networks:
      - homeserver

networks:
  homeserver:
    name: homeserver
    external: true
