# https://github.com/meeb/tubesync

version: "3.8"
services:
  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    restart: always
    volumes:
      - /volume1/docker/tubesync/downloads:/downloads
      - /volume1/docker/tubesync/config:/config
    security_opt:
      - no-new-privileges:true
    networks:
      - homeserver
    environment:
      - TZ=Europe/Warsaw
      - GUNICORN_WORKERS=1
      - PUID=1000
      - PGID=1000
    labels:
      - traefik.enable=true
      - traefik.http.routers.tubesync.rule=Host(`tubesync.${SERVER_DOMAIN}`)
      - traefik.http.routers.tubesync.entrypoints=websecure
      - traefik.http.routers.tubesync.tls.certresolver=myresolver
      - traefik.http.services.tubesync.loadbalancer.server.port=4848
      - traefik.docker.network=homeserver


networks:
  homeserver:
    name: homeserver
    external: true
