# https://github.com/meeb/tubesync

version: "3.8"
services:
  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    restart: always
    network_mode: "container:gluetun"
    volumes:
      - /volume1/docker/tubesync/downloads:/downloads
      - /volume1/docker/tubesync/config:/config
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Warsaw
      - GUNICORN_WORKERS=1
      - PUID=1000
      - PGID=1000


networks:
  homeserver:
    name: homeserver
    external: true
