# https://github.com/meeb/tubesync

version: "3.8"
services:
  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    restart: always
    volumes:
      - tubesync_downloads:/downloads
      - tubesync_config:/config
    security_opt:
      - no-new-privileges:true
    networks:
      - homeserver
    environment:
      - TZ=Europe/Warsaw
      - GUNICORN_WORKERS=1
      - PUID=1000
      - PGID=1000


networks:
  homeserver:
    name: homeserver
    external: true

volumes:
  tubesync_downloads:
  tubesync_config: