version: "3.8"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /volume1/docker/heimdall/config:/config
    container_name: heimdall
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - homeserver
    labels:
      - "my.zone=homeserver"
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`heimdall.${SERVER_DOMAIN}`)"
      - "traefik.http.routers.heimdall.entrypoints=websecure"
      - "traefik.http.routers.heimdall.tls.certresolver=myresolver"
      - "traefik.http.services.heimdall.loadbalancer.server.port=80"
      - "traefik.docker.network=homeserver"

networks:
  homeserver:
    name: homeserver
    external: true
