version: "3.8"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - heimdall-volume:/config
    container_name: heimdall
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - homeserver

networks:
  homeserver:
    name: homeserver
    external: true

volumes:
  heimdall-volume: