version: "3.8"

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8080:8080"   # qbittorrent
      - "8081:8081"   # metube
    volumes:
      - /volume1/docker/gluetun/config:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER:-surfshark}
      - VPN_TYPE=${VPN_TYPE:-wireguard}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - TZ=${TZ:-UTC}
      # Health check URL for VPN status
      - HTTPPROXY=on
      - HTTPPROXY_LOG=on
    networks:
      - homeserver
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "my.zone=homeserver"
      - "traefik.enable=true"
      # qbittorrent routing
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.${SERVER_DOMAIN}`)"
      - "traefik.http.routers.qbittorrent.entrypoints=websecure"
      - "traefik.http.routers.qbittorrent.tls.certresolver=myresolver"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
      # metube routing  
      - "traefik.http.routers.metube.rule=Host(`metube.${SERVER_DOMAIN}`)"
      - "traefik.http.routers.metube.entrypoints=websecure"
      - "traefik.http.routers.metube.tls.certresolver=myresolver"
      - "traefik.http.services.metube.loadbalancer.server.port=8081"

networks:
  homeserver:
    name: homeserver
    external: true