version: "3.8"

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - "8080:8080"
    volumes:
      - gluetun_data:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER:-surfshark}
      - VPN_TYPE=${VPN_TYPE:-wireguard}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_COUNTRIES=${VPN_SERVICE_PROVIDER:-Slovakia}
      - TZ=${TZ:-Europe/Warsaw}
    networks:
      - homeserver
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  whoami:
    image: traefik/whoami:latest
    container_name: whoami-vpn
    network_mode: "service:gluetun"

networks:
  homeserver:
    name: homeserver
    external: true

volumes:
  gluetun_data: