version: "3.8"

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - "8080:8080"
      - "8081:80"
    volumes:
      - gluetun_data:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER:-surfshark}
      - VPN_TYPE=${VPN_TYPE:-wireguard}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - WIREGUARD_DNS=${WIREGUARD_DNS:-1.1.1.1}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES:-Slovakia}
      - TZ=${TZ:-Europe/Warsaw}
      - FIREWALL_OUTBOUND_SUBNETS=${FIREWALL_OUTBOUND_SUBNETS:-172.18.0.0/16}
      - FIREWALL_INPUT_PORTS=8081
      - FIREWALL=off
    networks:
      - homeserver
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  whoami:
    image: traefik/whoami:latest
    container_name: whoami
    network_mode: "service:gluetun"

networks:
  homeserver:
    name: homeserver
    external: true

volumes:
  gluetun_data: